### ISSUE TITLE
unable to run code 

### ISSUE THREAD

**Issue by kennyboi2017** [ATBlastDon/Library-Management#1]
hello 
thanks for this code but i have an issue i need your assistance on 
i have meet all requirement but i cant seem to run the code by using the python <file location > command 
pls can you offer your assistance

**Comment by ATBlastDon** [comment]
Yess
Whats the issue??
Bcoz its simple Library Management Project 
You need MySQL Database only ( That also provided in code so you only have to install Xampp and turn on that MySQL Toggle ) 
You just need to install require Python extenstions like TKinter 
And run that code
